### ISSUE TITLE
Example of parser entering the infinite loop ?

### ISSUE THREAD

**Issue by jlgrall** [tanakahisateru/js-markdown-extra#35]
Could someone give me an (or a few different) example of text that triggers the infinite loop ?

**Comment by michelf** [comment]
Just try a simple link in Chrome or Firefox (Safari seems imune):

```
[text text text text text text](url)
```

The longer the text is, the very much longer it takes to parse. Technically it's not an infinite loop, but if it's going to take a few days to process there isn't much difference. This is probably caused by excessive backtracking; there's a reason the PHP version uses once-only `(?>` groups at so many places. I would assume Safari's regex optimizer is better at seeing when it can avoid backtracking.

**Comment by michelf** [comment]
I fixed the problem above by simply discarding support for nested brackets and parenthesis, replacing the two variables with this:

```
this.nested_brackets_re = '(?:[^\\]]*?)';
this.nested_url_parenthesis_re = '(?:[^\\)\\s]*?)';
```

This is where all the unnecessary backtracking was occurring due to the nested repetition blocks.

**Comment by tanakahisateru** [comment]
I've known how RegExp is slow.
Unfortunately, brackets and parenthesis nesting should not be supported.
